#!/bin/sh -e
#
# FreeBSD hotplug script for attaching xnb* interfaces to bridges
#
# Parameters:
#	$1: xenstore backend path of the vif
#	$2: action, either "add" or "remove"
#
# Environment variables:
#	$iface_dev: name of the backend device (xnb<domid>.<handle>)
#

DIR=$(dirname "$0")
. "${DIR}/hotplugpath.sh"

PATH=${BINDIR}:${SBINDIR}:${LIBEXEC}:${PRIVATE_BINDIR}:/bin:/usr/bin:/sbin:/usr/sbin
export PATH

xpath=$1
xaction=$2

case $xaction in
add)
	xbridge=$(xenstore-read "$xpath/bridge")
	ifconfig $xbridge addm $iface_dev
	ifconfig $iface_dev up
	exit 0
	;;
remove)
	if [ "$emulated" -eq 1 ]; then
		xbridge=$(xenstore-read "$xpath/bridge")
		ifconfig $iface_dev down
		ifconfig $xbridge deletem $iface_dev
		ifconfig $iface_dev destroy
	fi
	exit 0
	;;
*)
	exit 0
	;;
esac
