/* SPDX-License-Identifier: GPL-2.0 */

#include <asm/test.h>

/*
 * Interesting case because `return false` can be encoded as `xor %eax, %eax`,
 * which is shorter than `return true` which is encoded as a `mov $1, %eax`
 * instruction (based on code generated by GCC 13.2 at -O2), and also shorter
 * than the replacement `jmp` instruction.
 */
bool cf_check test_lp_insn_replacement(void)
{
    return true;
}

/*
 * Local variables:
 * mode: C
 * c-file-style: "BSD"
 * c-basic-offset: 4
 * tab-width: 4
 * indent-tabs-mode: nil
 * End:
 */
