#!/bin/bash -ex

# Set HOST{CC/CXX} in case we are cross building
export HOSTCC=${CC}
export HOSTCXX=${CXX}
# Prefix environment CC/CXX with CROSS_COMPILE if present
export CC=${CROSS_COMPILE}${CC}
export CXX=${CROSS_COMPILE}${CXX}

$CC --version
[[ "${CC}" != "${HOSTCC}" ]] && $HOSTCC --version

# random config or default config
if [[ "${RANDCONFIG}" == "y" ]]; then
    make -C xen KCONFIG_ALLCONFIG=tools/kconfig/allrandom.config randconfig
else
    make -C xen defconfig
fi

# build up our configure options
cfgargs=()
cfgargs+=("--disable-stubdom") # more work needed into building this
cfgargs+=("--disable-rombios")
cfgargs+=("--enable-docs")
cfgargs+=("--with-system-seabios=/usr/share/seabios/bios.bin")

if [[ "${XEN_TARGET_ARCH}" == "x86_64" ]]; then
    cfgargs+=("--enable-tools")
else
    cfgargs+=("--disable-tools") # we don't have the cross depends installed
fi

./configure "${cfgargs[@]}"

make dist
